-- საძმაკაცოს საერთო Database — Supabase
-- SQL Editor-ში ჩასვი მთლიანად და Run დააჭირე.

create table if not exists public.sadzmakacoso_responses (
  id bigint generated by default as identity primary key,
  room_id text not null,
  member_name text not null,
  status text not null default 'unknown'
    check (status in ('unknown','yes','maybe','no')),
  location text,
  foods jsonb not null default '[]'::jsonb,
  activity text,
  event_date date,
  event_time time,
  updated_at timestamptz not null default now(),
  unique (room_id, member_name)
);

-- RLS
alter table public.sadzmakacoso_responses enable row level security;

-- ბრაუზერიდან გამოყენებულ anon/publishable როლს ვაძლევთ ცხრილზე საჭირო უფლებებს.
grant select, insert, update on table public.sadzmakacoso_responses to anon;
grant usage, select on sequence public.sadzmakacoso_responses_id_seq to anon;

-- ოთხივე წევრს სჭირდება საერთო ოთახის ჩანაწერების ნახვა/შენახვა.
drop policy if exists "sadzmakacoso public read" on public.sadzmakacoso_responses;
create policy "sadzmakacoso public read"
on public.sadzmakacoso_responses
for select
to anon
using (true);

drop policy if exists "sadzmakacoso public insert" on public.sadzmakacoso_responses;
create policy "sadzmakacoso public insert"
on public.sadzmakacoso_responses
for insert
to anon
with check (true);

drop policy if exists "sadzmakacoso public update" on public.sadzmakacoso_responses;
create policy "sadzmakacoso public update"
on public.sadzmakacoso_responses
for update
to anon
using (true)
with check (true);

-- Realtime: მხოლოდ მაშინ დაამატე publication-ში, თუ ჯერ არ არის.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sadzmakacoso_responses'
  ) then
    alter publication supabase_realtime
      add table public.sadzmakacoso_responses;
  end if;
end $$;

-- შემოწმება: ამ query-მ ცხრილი უნდა დააბრუნოს.
select *
from public.sadzmakacoso_responses
order by updated_at desc;

-- სურვილის შემთხვევაში ძველი პასუხების გასუფთავება:
-- delete from public.sadzmakacoso_responses
-- where room_id = 'sadzmakacoso-2026';
